return {
    ["Magnus"] = {
        ["Missing Pocketwatch"] = {
            ["Description"] = "Find Magnus' pocketwatch at one of the stands in central city, be careful not to make any trouble",
            ["Rewards"] = {
                ["Items"] = {
                    ["Library Pass"] = 1
                },
                ["Experience"] = math.random(70, 120),
                ["Alignment"] = 1
            }
        }
    },
    ["Sam"] = {
        ["Military Exam"] = {
            ["Description"] = "Head over to the central command center to begin your exam.",
            ["Rewards"] = {
                ["Items"] = {
                    ["Uniform"] = 1
                },
                ["Experience"] = math.random(70, 120),
                ["Alignment"] = 1
            }
        }
    }
}