--!strict
--!native
--!optimize 2
--!nolint LocalShadow
--#selene: allow(shadowing)
-- File generated by Blink v0.18.0 (https://github.com/1Axen/Blink)
-- This file is not meant to be edited

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local BASE_EVENT_NAME = "CHRONO_BLINK"
local Invocations = 0

local SendSize = 64
local SendOffset = 0
local SendCursor = 0
local SendBuffer = buffer.create(64)
local SendInstances = {}

local RecieveCursor = 0
local RecieveBuffer = buffer.create(64)

local RecieveInstances = {}
local RecieveInstanceCursor = 0

local Null = newproxy()

type Entry = {
    value: any,
    next: Entry?
}

type Queue = {
    head: Entry?,
    tail: Entry?
}

type BufferSave = {
    Size: number, 
    Cursor: number, 
    Buffer: buffer, 
    Instances: {Instance}
}

local function Read(Bytes: number)
    local Offset = RecieveCursor
    RecieveCursor += Bytes
    return Offset
end

local function Save(): BufferSave
    return {
        Size = SendSize,
        Cursor = SendCursor,
        Buffer = SendBuffer,
        Instances = SendInstances
    }
end

local function Load(Save: BufferSave?)
    if Save then
        SendSize = Save.Size
        SendCursor = Save.Cursor
        SendOffset = Save.Cursor
        SendBuffer = Save.Buffer
        SendInstances = Save.Instances
        return
    end

    SendSize = 64
    SendCursor = 0
    SendOffset = 0
    SendBuffer = buffer.create(64)
    SendInstances = {}
end

local function Invoke()
    if Invocations == 255 then
        Invocations = 0
    end

    local Invocation = Invocations
    Invocations += 1
    return Invocation
end

local function Allocate(Bytes: number)
    local InUse = (SendCursor + Bytes)
    if InUse > SendSize then
        --> Avoid resizing the buffer for every write
        while InUse > SendSize do
            SendSize *= 1.5
        end

        local Buffer = buffer.create(SendSize)
        buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
        SendBuffer = Buffer
    end

    SendOffset = SendCursor
    SendCursor += Bytes
    
    return SendOffset
end

local function CreateQueue(): Queue
    return {
        head = nil,
        tail = nil
    }
end

local function Pop(queue: Queue): any
    local head = queue.head
    if head == nil then
        return
    end

    queue.head = head.next
    return head.value
end

local function Push(queue: Queue, value: any)
    local entry: Entry = {
        value = value,
        next = nil
    }

    if queue.tail ~= nil then
        queue.tail.next = entry
    end

    queue.tail = entry

    if queue.head == nil then
        queue.head = entry
    end
end

local Calls = table.create(256)

local Events: any = {
    Reliable = table.create(256),
    Unreliable = table.create(256)
}

local Queue: any = {
    Reliable = table.create(256),
    Unreliable = table.create(256)
}

Queue.Unreliable[0] = table.create(256)
export type Transform = { Position: Vector3, RotationY: number }
local function ReadEVENT_ClientReplicateCFrame(): ({ timestamp: number, cframe: { Position: Vector3, RotationY: number } })
	-- Read BLOCK: 18 bytes
	local BLOCK_START = Read(18)
	local Value = {} :: any
	Value.timestamp = buffer.readf32(RecieveBuffer, BLOCK_START + 0)
	Value.cframe = {} :: any
	local X = buffer.readf32(RecieveBuffer, BLOCK_START + 4)
	local Y = buffer.readf32(RecieveBuffer, BLOCK_START + 8)
	local Z = buffer.readf32(RecieveBuffer, BLOCK_START + 12)
	Value.cframe.Position = Vector3.new(X, Y, Z)
	local Encoded = buffer.readu16(RecieveBuffer, BLOCK_START + 16)
	local MantissaExponent = Encoded % 0x8000
	if MantissaExponent == 0b0_11111_0000000000  then
		if Encoded // 0x8000 == 1 then
			Value.cframe.RotationY = -math.huge
		else
			Value.cframe.RotationY = math.huge
		end
	elseif MantissaExponent == 0b1_11111_0000000000   then
		Value.cframe.RotationY = 0 / 0
	elseif MantissaExponent == 0b0_00000_0000000000   then
		Value.cframe.RotationY = 0
	else
		local Mantissa = MantissaExponent % 0x400
		local Exponent = MantissaExponent // 0x400
		local Fraction;
		if Exponent == 0 then
			Fraction = Mantissa / 0x400
		else
			Fraction = Mantissa / 0x800 + 0.5
		end
		local Result = math.ldexp(Fraction, Exponent - 14)
		Value.cframe.RotationY = if Encoded // 0x8000 == 1 then -Result else Result
	end
	return Value
end

local function WriteEVENT_ServerReplicateCFrame(Value: { timestamps: {[number]: number}, cframes: {[number]: { Position: Vector3, RotationY: number }} }): ()
	-- Allocate BLOCK: 5 bytes
	local BLOCK_START = Allocate(5)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 1)
	local Elements_1 = 0
	for Key_1, Element_1 in Value.timestamps do
		Elements_1 += 1
		local OFFSET_0 = Allocate(2)
		buffer.writeu16(SendBuffer, OFFSET_0, Key_1)
		local OFFSET_1 = Allocate(4)
		buffer.writef32(SendBuffer, OFFSET_1, Element_1)
	end
	buffer.writeu16(SendBuffer, BLOCK_START + 1, Elements_1)
	local Elements_1 = 0
	for Key_1, Element_1 in Value.cframes do
		Elements_1 += 1
		local OFFSET_0 = Allocate(2)
		buffer.writeu16(SendBuffer, OFFSET_0, Key_1)
		local Vector = Element_1.Position
		local OFFSET_1 = Allocate(4)
		buffer.writef32(SendBuffer, OFFSET_1, Vector.X)
		local OFFSET_2 = Allocate(4)
		buffer.writef32(SendBuffer, OFFSET_2, Vector.Y)
		local OFFSET_3 = Allocate(4)
		buffer.writef32(SendBuffer, OFFSET_3, Vector.Z)
		local OFFSET_4 = Allocate(2)
		if Element_1.RotationY > 65504 then
			buffer.writeu16(SendBuffer, OFFSET_4, 0b0_11111_0000000000)
		elseif Element_1.RotationY < -65504 then
			buffer.writeu16(SendBuffer, OFFSET_4, 0b1_11111_0000000000)
		elseif Element_1.RotationY ~= Element_1.RotationY then
			buffer.writeu16(SendBuffer, OFFSET_4, 0b1_11111_0000000001)
		elseif Element_1.RotationY == 0 then
			buffer.writeu16(SendBuffer, OFFSET_4, 0)
		else
			local float = Element_1.RotationY
			local Abosulte = math.abs(float)
			local Interval = math.ldexp(1, math.floor(math.log(Abosulte, 2)) - 10)
			local RoundedValue = (Abosulte // Interval) * Interval
			local Fraction, Exponent = math.frexp(RoundedValue)
			Exponent += 14
			local Mantissa = math.round(if Exponent <= 0
				then Fraction * 0x400 / math.ldexp(1, math.abs(Exponent))
				else Fraction * 0x800) % 0x400
			local Result = Mantissa
				+ math.max(Exponent, 0) * 0x400
				+ if float < 0 then 0x8000 else 0
			buffer.writeu16(SendBuffer, OFFSET_4, Result)
		end
	end
	buffer.writeu16(SendBuffer, BLOCK_START + 3, Elements_1)
end

local function WriteEVENT_TickRateChanged(Value: { id: number, tickRate: number }): ()
	-- Allocate BLOCK: 7 bytes
	local BLOCK_START = Allocate(7)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 0)
	buffer.writeu16(SendBuffer, BLOCK_START + 1, Value.id)
	buffer.writef32(SendBuffer, BLOCK_START + 3, Value.tickRate)
end

local function WriteEVENT_TogglePlayerReplication(Value: { id: number, on: boolean }): ()
	-- Allocate BLOCK: 4 bytes
	local BLOCK_START = Allocate(4)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 1)
	buffer.writeu16(SendBuffer, BLOCK_START + 1, Value.id)
	buffer.writeu8(SendBuffer, BLOCK_START + 3, Value.on and 1 or 0)
end

local function WriteEVENT_InitializePlayer(Value: { id: number, player: string }): ()
	-- Allocate BLOCK: 5 bytes
	local BLOCK_START = Allocate(5)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 2)
	buffer.writeu16(SendBuffer, BLOCK_START + 1, Value.id)
	local Length = #Value.player
	buffer.writeu16(SendBuffer, BLOCK_START + 3, Length)
	Allocate(Length)
	buffer.writestring(SendBuffer, SendOffset, Value.player, Length)
end

local function WriteEVENT_InitializeExistingPlayers(Value: { { id: number, player: string } }): ()
	-- Allocate BLOCK: 3 bytes
	local BLOCK_START = Allocate(3)
	buffer.writeu8(SendBuffer, BLOCK_START + 0, 3)
	-- START ARRAY
	buffer.writeu16(SendBuffer, BLOCK_START + 1, #Value)
		-- Allocate BLOCK: 4 bytes
	local ARRAY_START_1 = Allocate(4 * #Value)
	for Index = 1, #Value do
		local Item_1 = Value[Index]
		-- Allocate 2
		local OPERATION_OFFSET_0 = ARRAY_START_1
		ARRAY_START_1 += 2
		buffer.writeu16(SendBuffer, OPERATION_OFFSET_0, Item_1.id)
		local Length = #Item_1.player
		-- Allocate 2
		local OPERATION_OFFSET_1 = ARRAY_START_1
		ARRAY_START_1 += 2
		buffer.writeu16(SendBuffer, OPERATION_OFFSET_1, Length)
		Allocate(Length)
		buffer.writestring(SendBuffer, SendOffset, Item_1.player, Length)
	end
	-- END ARRAY
end

if not RunService:IsRunning() then
	local NOOP = function() end
	local Returns = table.freeze({
	ClientReplicateCFrame = {
		On = NOOP
	},
	ServerReplicateCFrame = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	TickRateChanged = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	TogglePlayerReplication = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	InitializePlayer = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	InitializeExistingPlayers = {
		Fire = NOOP,
		FireAll = NOOP,
		FireList = NOOP,
		FireExcept = NOOP
	},
	})
	return Returns :: BLINK_EVENTS_SYMBOL
end

if not RunService:IsServer() then
    error("Server network module can only be required from the server.")
end

local Reliable: RemoteEvent = ReplicatedStorage:FindFirstChild(BASE_EVENT_NAME .. "_RELIABLE_REMOTE") :: RemoteEvent
if not Reliable then
    local RemoteEvent = Instance.new("RemoteEvent")
    RemoteEvent.Name = BASE_EVENT_NAME .. "_RELIABLE_REMOTE"
    RemoteEvent.Parent = ReplicatedStorage
    Reliable = RemoteEvent
end

local Unreliable: UnreliableRemoteEvent = ReplicatedStorage:FindFirstChild(BASE_EVENT_NAME .. "_UNRELIABLE_REMOTE") :: UnreliableRemoteEvent
if not Unreliable then
    local UnreliableRemoteEvent = Instance.new("UnreliableRemoteEvent")
    UnreliableRemoteEvent.Name = BASE_EVENT_NAME .. "_UNRELIABLE_REMOTE"
    UnreliableRemoteEvent.Parent = ReplicatedStorage
    Unreliable = UnreliableRemoteEvent
end

local PlayersMap: {[Player]: BufferSave} = {}

Players.PlayerRemoving:Connect(function(Player)
    PlayersMap[Player] = nil
end)

local function StepReplication()
    for Player, Send in PlayersMap do
        if Send.Cursor <= 0 then
            continue
        end

        local Buffer = buffer.create(Send.Cursor)
        buffer.copy(Buffer, 0, Send.Buffer, 0, Send.Cursor)
        Reliable:FireClient(Player, Buffer, Send.Instances)

        Send.Size = 64
        Send.Cursor = 0
        Send.Buffer = buffer.create(64)
        table.clear(Send.Instances)
    end
end
RunService.Heartbeat:Connect(StepReplication)
Reliable.OnServerEvent:Connect(function(Player: Player, Buffer: buffer, Instances: {Instance})
	RecieveCursor = 0
	RecieveBuffer = Buffer
	RecieveInstances = Instances
	RecieveInstanceCursor = 0
	local Size = buffer.len(RecieveBuffer)
	while (RecieveCursor < Size) do
		-- Read BLOCK: 1 bytes
		local BLOCK_START = Read(1)
		local Index = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
	end
end)
Unreliable.OnServerEvent:Connect(function(Player: Player, Buffer: buffer, Instances: {Instance})
	RecieveCursor = 0
	RecieveBuffer = Buffer
	RecieveInstances = Instances
	RecieveInstanceCursor = 0
	local Size = buffer.len(RecieveBuffer)
	while (RecieveCursor < Size) do
		-- Read BLOCK: 1 bytes
		local BLOCK_START = Read(1)
		local Index = buffer.readu8(RecieveBuffer, BLOCK_START + 0)
		if Index == 0 then
			local Value: { timestamp: number, cframe: { Position: Vector3, RotationY: number } } = ReadEVENT_ClientReplicateCFrame()
			if Events.Unreliable[0] ~= nil then
				Events.Unreliable[0](Player, Value)
			end
		end
	end
end)


local Returns = table.freeze({
	StepReplication = StepReplication,

	ClientReplicateCFrame = {
		On = function(Listener: (Player: Player, Value: { timestamp: number, cframe: { Position: Vector3, RotationY: number } }) -> ()): () -> ()
			Events.Unreliable[0] = Listener
			return function (): ()
				if Events.Unreliable[0] == Listener then
					Events.Unreliable[0] = nil
				end
			end
		end
	},
	ServerReplicateCFrame = {
		Fire = function(Player: Player, Value: { timestamps: {[number]: number}, cframes: {[number]: { Position: Vector3, RotationY: number }} }): ()
			Load()
			WriteEVENT_ServerReplicateCFrame(Value)
			local Buffer = buffer.create(SendCursor)
			buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
			Unreliable:FireClient(Player, Buffer, SendInstances)
		end,
		FireAll = function(Value: { timestamps: {[number]: number}, cframes: {[number]: { Position: Vector3, RotationY: number }} }): ()
			Load()
			WriteEVENT_ServerReplicateCFrame(Value)
			local Buffer = buffer.create(SendCursor)
			buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
			Unreliable:FireAllClients(Buffer, SendInstances)
		end,
		FireList = function(List: {Player}, Value: { timestamps: {[number]: number}, cframes: {[number]: { Position: Vector3, RotationY: number }} }): ()
			Load()
			WriteEVENT_ServerReplicateCFrame(Value)
			local Buffer = buffer.create(SendCursor)
			buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
			for _, Player in List do
				Unreliable:FireClient(Player, Buffer, SendInstances)
			end
		end,
		FireExcept = function(Except: Player, Value: { timestamps: {[number]: number}, cframes: {[number]: { Position: Vector3, RotationY: number }} }): ()
			Load()
			WriteEVENT_ServerReplicateCFrame(Value)
			local Buffer = buffer.create(SendCursor)
			buffer.copy(Buffer, 0, SendBuffer, 0, SendCursor)
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Unreliable:FireClient(Player, Buffer, SendInstances)
			end
		end,
	},
	TickRateChanged = {
		Fire = function(Player: Player, Value: { id: number, tickRate: number }): ()
			Load(PlayersMap[Player])
			WriteEVENT_TickRateChanged(Value)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value: { id: number, tickRate: number }): ()
			Load()
			WriteEVENT_TickRateChanged(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value: { id: number, tickRate: number }): ()
			Load()
			WriteEVENT_TickRateChanged(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value: { id: number, tickRate: number }): ()
			Load()
			WriteEVENT_TickRateChanged(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
	TogglePlayerReplication = {
		Fire = function(Player: Player, Value: { id: number, on: boolean }): ()
			Load(PlayersMap[Player])
			WriteEVENT_TogglePlayerReplication(Value)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value: { id: number, on: boolean }): ()
			Load()
			WriteEVENT_TogglePlayerReplication(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value: { id: number, on: boolean }): ()
			Load()
			WriteEVENT_TogglePlayerReplication(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value: { id: number, on: boolean }): ()
			Load()
			WriteEVENT_TogglePlayerReplication(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
	InitializePlayer = {
		Fire = function(Player: Player, Value: { id: number, player: string }): ()
			Load(PlayersMap[Player])
			WriteEVENT_InitializePlayer(Value)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value: { id: number, player: string }): ()
			Load()
			WriteEVENT_InitializePlayer(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value: { id: number, player: string }): ()
			Load()
			WriteEVENT_InitializePlayer(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value: { id: number, player: string }): ()
			Load()
			WriteEVENT_InitializePlayer(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
	InitializeExistingPlayers = {
		Fire = function(Player: Player, Value: { { id: number, player: string } }): ()
			Load(PlayersMap[Player])
			WriteEVENT_InitializeExistingPlayers(Value)
			PlayersMap[Player] = Save()
		end,
		FireAll = function(Value: { { id: number, player: string } }): ()
			Load()
			WriteEVENT_InitializeExistingPlayers(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireList = function(List: {Player}, Value: { { id: number, player: string } }): ()
			Load()
			WriteEVENT_InitializeExistingPlayers(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in List do
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
		FireExcept = function(Except: Player, Value: { { id: number, player: string } }): ()
			Load()
			WriteEVENT_InitializeExistingPlayers(Value)
			local Buffer, Size, Instances = SendBuffer, SendCursor, SendInstances
			for _, Player in Players:GetPlayers() do
				if Player == Except then
					continue
				end
				Load(PlayersMap[Player])
				local Position = Allocate(Size)
				buffer.copy(SendBuffer, Position, Buffer, 0, Size)
				table.move(Instances, 1, #Instances, #SendInstances + 1, SendInstances)
				PlayersMap[Player] = Save()
			end
		end,
	},
})
type BLINK_EVENTS_SYMBOL = typeof(Returns)
return Returns :: BLINK_EVENTS_SYMBOL