return {
	One = {
		Cooldown = 1,
		Last_Used = 0,
		Windup = 0.7,
		Endlag = 0.35,
		Guardbreak = false,
		MasteryRequirement = 0,
		Quirk = script.Name, 
		KeyText = "Z",
		Description = "NIL",
		Name = "Flame Combust",
	},
	Two = {
		Cooldown = 1,
		Last_Used = 0,
		Windup = 0.4,
		Endlag = 1.25,
		Guardbreak = false,
		MasteryRequirement = 0,
		Quirk = script.Name, 
		KeyText = "X",
		Description = "NIL",
		Name = "Incinerate",
	},
	Three = {
		Cooldown = 1,
		Last_Used = 0,
		Windup = 0.6,
		Endlag = 1.7,
		Guardbreak = false,
		MasteryRequirement = 0,
		Quirk = script.Name,
		KeyText = "C",
		Description = "NIL",
		Name = "Prominence Burn",
	},
	Four = {
		Cooldown = 1,
		Last_Used = 0,
		Windup = 0.5,
		Endlag = 0.35,
		Guardbreak = false,
		MasteryRequirement = 0,
		Quirk = script.Name, 
		KeyText = "V",
		Description = "NIL",
		Name =  "Schorching blade"--"Plus Ultra Prominence Burn",
	},
}