return {
	NPCName = "Sam",
	Nodes = {
		{
			Name = "Root",
			Type = "DialogueRoot",
			Priority = 0,
			Outputs = { "NenGreeting" },
		},

		{
			Name = "NenGreeting",
			Type = "Prompt",
			Priority = 0,
			Text = "I sense potential within you... Have you ever heard of Nen? It is the ability to use and manipulate your own life energy, or aura.",
			Outputs = { "YesResponse", "NoResponse" },
		},
		{
			Name = "YesResponse",
			Type = "Response",
			Priority = 0,
			Text = "I want to learn about it",
			Outputs = { "NenExplanation" },
		},
		{
			Name = "NoResponse",
			Type = "Response",
			Priority = 0,
			Text = "I'm not interested",
			Outputs = { "Goodbye" },
		},
		{
			Name = "NenExplanation",
			Type = "Prompt",
			Priority = 0,
			Text = "Nen is a powerful technique that allows one to control the flow of their aura. But first, you must awaken it. Are you ready to begin?",
			Outputs = { "ReadyResponse", "NotReadyResponse" },
		},
		{
			Name = "ReadyResponse",
			Type = "Response",
			Priority = 0,
			Text = "I'm ready",
			Outputs = { "GiveCup" },
		},
		{
			Name = "NotReadyResponse",
			Type = "Response",
			Priority = 0,
			Text = "Not yet",
			Outputs = { "ComeBack" },
		},
		{
			Name = "GiveCup",
			Type = "Prompt",
			Priority = 0,
			Text = "Take this sacred cup. Go to the meditation point and drink from it. The water will help open your aura nodes. Focus your mind and let the energy flow through you.",
			Quest = {
				Action = "Accept",
				QuestName = "Nen Awakening",
			},
			Outputs = {},
		},
		{
			Name = "ComeBack",
			Type = "Prompt",
			Priority = 0,
			Text = "Return when you are ready to begin your journey into Nen.",
			Outputs = {},
			AutoClose = true,
		},
		{
			Name = "Goodbye",
			Type = "Prompt",
			Priority = 0,
			Text = "Perhaps another time then. The path of Nen is not for everyone.",
			Outputs = {},
			AutoClose = true,
		},
		{
			Name = "End",
			Type = "Prompt",
			Priority = 0,
			Text = "",
			Outputs = {},
			AutoClose = true,
		},
	},
}
